framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - doctrine_transaction
      query.bus:
      event.bus:
        default_middleware:
          enabled: true
          # set "allow_no_handlers" to true (default is false) to allow having
          # no handler configured for this bus without throwing an exception
          allow_no_handlers: true
          # set "allow_no_senders" to false (default is true) to throw an exception
          # if no sender is configured for this bus
          allow_no_senders: true

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'

    routing:
      # Route your messages to the transports
      # 'App\Message\YourMessage': async
      App\Common\CQRS\AsyncMessage: async
      App\Common\CQRS\SyncMessage: sync
      'Symfony\Component\Mailer\Messenger\SendEmailMessage': async

when@test:
  framework:
    messenger:
      transports:
        async: 'in-memory://'
        sync: 'in-memory://'
