framework:
  rate_limiter:
    verification_link_resend_api:
      policy: 'fixed_window'
      limit: 1
      interval: '60 seconds'
    anonymous_api:
      policy: 'fixed_window'
      limit: 2
      interval: '15 minutes'
    authenticated_api:
      policy: 'token_bucket'
      limit: 1
      rate: { interval: '15 minutes', amount: 1 }
