name: Deploy <env>
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Pre-deploy checks
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

# deploy action here
